import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { createTheme, ThemeProvider } from '@mui/material/styles'
import Header from '../components/Header'
import NotificationBar from '../components/Notifications'
import EventCarousel from '../components/Events'
import TrendingNow from '../components/Trending'
import DealsOfDay from '../components/Deals'
import EventProduct from '../components/Events/EventProduct'
import Categories from '../components/Categories'

const Home: NextPage = () => {
  const theme = createTheme({
    typography: {
      fontFamily: [
        'Libre Baskerville',
        'Arial',
        'sans-serif'
      ].join(','),
    },

    palette: {
      primary: {
        main: '#272727',
      },
      secondary: {
        main: '#fff',
      }
    },
  });

  theme.typography.h4 = {
    fontSize: '1.8rem',
    fontWeight: 400,
    [theme.breakpoints.up('sm')]: {
      fontSize: '1.6rem',
    },
    [theme.breakpoints.up('md')]: {
      fontSize: '2.125rem',
    },
  };

  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Globex Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header theme={theme}/>
      <NotificationBar theme={theme} />
      <EventCarousel theme={theme} />
      <TrendingNow theme={theme} />
      <DealsOfDay theme={theme} />
      <EventProduct theme={theme} />
      <Categories theme={theme} />
    </ThemeProvider>
  )
}

export default Home